name: Build Docker Image Template
on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      version:
        required: true
        type: string
env:
  DOCKER_IMAGE: ghcr.io/d34dplayer/litecli
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: jorgebg/stateful-action@v0.3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.docker_image }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ inputs.version }}
            type=schedule
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ${{ inputs.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ inputs.version }}
